name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install deps
      run : |
        pip install --upgrade pip pipenv
        pipenv sync --dev
        pipenv graph
    - name: Run Tests
      run: |
        pipenv sync --dev
        ls
        make install
        make tests
